app:
  connection-string: HostName=${iot-hub-name}.azure-devices.net;DeviceId=${device-id};SharedAccessKey=${access-key}
  path-to-certificate: ${path-certificate}
  scope-id: xxx
  global-endpoint: xxxx
  symmetric-key: xxx
  registration-id: xx
